/-
# MiniTensorAlgebra.Constructions.Quotients

Quotient constructions: symmetric algebra as quotient
of tensor algebra, exterior algebra as quotient, and
related quotient spaces.
-/

import MiniTensorAlgebra.Core.Basic
import MiniTensorAlgebra.Core.Laws

namespace MiniTensorAlgebra

open MiniVectorSpaceCore

/-! ## Symmetric Algebra as Quotient -/

structure SymmetricQuotient (F : Field) (V : VectorSpace F) where
  T : VectorSpace F
  -- S(V) = T(V) / ⟨x⊗y - y⊗x⟩
  ideal : T.V → Prop  -- ideal generated by commutators

/-! ## Exterior Algebra as Quotient -/

structure ExteriorQuotient (F : Field) (V : VectorSpace F) where
  T : VectorSpace F
  -- Λ(V) = T(V) / ⟨x⊗x⟩
  ideal : T.V → Prop  -- ideal generated by squares

/-! ## Two-Sided Ideal in Tensor Algebra -/

structure TwoSidedIdeal (F : Field) (V : VectorSpace F) where
  TA : TensorAlgebra F V
  I : TA.carrier → Prop
  isIdeal : Prop := True  -- closed under addition and multiplication by elements of TA

/-! ## Quotient Algebra -/

structure QuotientAlgebra (F : Field) (V : VectorSpace F) where
  TA : TensorAlgebra F V
  ideal : TwoSidedIdeal F V
  carrier : Type
  -- quotient space with induced multiplication

/-! ## Universal Enveloping Algebra (conceptual) -/

structure UniversalEnvelopingAlgebra (F : Field) (V : VectorSpace F) where
  U : VectorSpace F
  -- Quotient of tensor algebra by the Lie ideal

#eval "Constructions.Quotients: SymmetricQuotient, ExteriorQuotient, TwoSidedIdeal, QuotientAlgebra"
