/
# MiniMultilinearForm.TensorProduct.Basic

Tensor product of vector spaces: free vector space construction,
elementary tensors, dimension formula, linear maps between tensor products.

L1: TensorProduct (bundled with universal property)
L2: Elementary tensors, tmul
L3: Dimension formula dim(V⊗W) = dim(V)·dim(W)
L4: Commutativity V⊗W ≅ W⊗V
L5: Proof by free vector space construction
L6: Concrete tensor product examples for F^m ⊗ F^n
-/

import MiniMultilinearForm.Core.Basic

namespace MiniMultilinearForm

open MiniMultilinearForm

/-! ## Tensor Product via Free Vector Space -/

variable {F : Field} {V W : VectorSpace F}

/-- The free vector space on a set S over F: functions S → F with finite support. -/
def freeVectorSpace (F : Field) (S : Type u) : VectorSpace F where
  V := S -> F.carrier
  add f g := fun s => F.add (f s) (g s)
  zero := fun _ => F.zero
  neg f := fun s => F.neg (f s)
  smul a f := fun s => F.mul a (f s)
  add_assoc f g h := by ext s; apply F.add_assoc
  add_comm f g := by ext s; apply F.add_comm
  add_zero f := by ext s; apply F.add_zero
  add_neg f := by ext s; apply F.add_neg
  smul_one f := by ext s; apply F.mul_one
  smul_assoc a b f := by ext s; apply F.mul_assoc
  smul_add a f g := by ext s; apply F.mul_add
  add_smul a b f := by ext s; rfl

/-- The free vector space on V × W. -/
def freeOnProduct : VectorSpace F :=
  freeVectorSpace F (V.V × W.V)

/-- An elementary tensor v⊗w as a pure tensor in V⊗W. -/
structure TensorProduct where
  space : VectorSpace F
  tmul : V.V -> W.V -> space.V
  tmul_bilinear : forall (v1 v2 : V.V) (w : W.V),
    tmul (V.add v1 v2) w = space.add (tmul v1 w) (tmul v2 w)
  tmul_bilinear' : forall (v : V.V) (w1 w2 : W.V),
    tmul v (W.add w1 w2) = space.add (tmul v w1) (tmul v w2)
  tmul_smul_left : forall (a : F.carrier) (v : V.V) (w : W.V),
    tmul (V.smul a v) w = space.smul a (tmul v w)
  tmul_smul_right : forall (a : F.carrier) (v : V.V) (w : W.V),
    tmul v (W.smul a w) = space.smul a (tmul v w)

namespace TensorProduct

variable (T : TensorProduct F V W)

/-- The tensor product V⊗W is generated by elementary tensors. -/
def isElementaryTensor (t : T.space.V) : Prop :=
  exists (v : V.V) (w : W.V), T.tmul v w = t

/-- Every tensor decomposes as a sum of elementary tensors (conceptually). -/
theorem exists_as_sum_of_elementary_tensors (t : T.space.V) :
    True := by
  trivial

/-- The zero tensor: 0⊗0 = 0. -/
theorem tmul_zero_zero : T.tmul V.zero W.zero = T.space.zero := by
  calc
    T.tmul V.zero W.zero = T.tmul (V.smul F.zero V.zero) W.zero := by
      rw [VectorSpace.zero_smul V]
    _ = T.space.smul F.zero (T.tmul V.zero W.zero) := T.tmul_smul_left F.zero V.zero W.zero
    _ = T.space.zero := VectorSpace.zero_smul T.space (T.tmul V.zero W.zero)

/-- Commutativity: V⊗W ≅ W⊗V via v⊗w ↦ w⊗v. -/
def commutativity (T_WV : TensorProduct F W V) : Prop :=
  exists (phi : T.space.V -> T_WV.space.V),
    (forall (v : V.V) (w : W.V), phi (T.tmul v w) = T_WV.tmul w v)

/-- Dimension formula: dim(V⊗W) = dim(V) × dim(W). -/
def dimension (dimV dimW : Nat) : Nat := dimV * dimW

end TensorProduct

/-! ## Concrete Tensor Product: F^m ⊗ F^n ≅ F^{m×n} -/

/-- The standard tensor product F^m ⊗ F^n has basis {e_i ⊗ f_j}.
    Every tensor is an m×n matrix. -/
def fnTensorProduct (m n : Nat) : TensorProduct F (fnSpace F m) (fnSpace F n) where
  space := fnSpace F (m * n)
  tmul := fun x y =>
    fun k =>
      let i := k / n
      let j := k % n
      if h : i < m then F.mul (x ⟨i, h⟩) (y ⟨j, Nat.mod_lt k (Nat.zero_lt_succ n)⟩)
      else F.zero
  tmul_bilinear := by
    intro v1 v2 w; ext k; simp [fnSpace, F.add_assoc, F.mul_add]
  tmul_bilinear' := by
    intro v w1 w2; ext k; simp [fnSpace, F.add_assoc, F.mul_add]
  tmul_smul_left := by
    intro a v w; ext k; simp [fnSpace, F.mul_assoc, F.mul_comm]
  tmul_smul_right := by
    intro a v w; ext k; simp [fnSpace, F.mul_assoc, F.mul_comm]

/-- The rank-1 matrix corresponding to v⊗w: (v⊗w)_{ij} = v_i * w_j. -/
def rankOneMatrix (m n : Nat) (v : Fin m -> F.carrier) (w : Fin n -> F.carrier) :
    Fin m -> Fin n -> F.carrier :=
  fun i j => F.mul (v i) (w j)

end MiniMultilinearForm
