/-
# MiniTensorAlgebra.Core.Basic

Tensor products of vector spaces, universal property,
tensor algebra, symmetric and exterior algebras.
-/

import MiniVectorSpaceCore.Core.Basic
import MiniLinearTransformation.Core.Basic
import MiniMultilinearForm.Core.Basic

namespace MiniTensorAlgebra

open MiniVectorSpaceCore
open MiniLinearTransformation
open MiniMultilinearForm

/-! ## Tensor Product (Universal Property) -/

structure TensorProduct (F : Field) (V W : VectorSpace F) where
  T : VectorSpace F
  ι : BilinearMap V W T
  universal : ∀ (U : VectorSpace F) (B : BilinearMap V W U),
    ∃! (f : LinearMap T U), ∀ (v : V.V) (w : W.V),
      f.map (ι.map v w) = B.map v w

/-! ## Simple Tensor -/

def simpleTensor {F : Field} {V W : VectorSpace F} (TP : TensorProduct F V W)
    (v : V.V) (w : W.V) : TP.T.V := TP.ι.map v w

notation:60 x:60 " ⊗ " y:60 => simpleTensor _ x y

/-! ## Tensor Product of Linear Maps -/

def tensorMap {F : Field} {V₁ V₂ W₁ W₂ : VectorSpace F}
    (f : LinearMap V₁ W₁) (g : LinearMap V₂ W₂)
    (TP₁ : TensorProduct F V₁ V₂) (TP₂ : TensorProduct F W₁ W₂) : LinearMap TP₁.T TP₂.T :=
  -- Given by universal property of TP₁ applied to ι₂ ∘ (f,g)
  LinearMap.id TP₁.T  -- conceptual placeholder

/-! ## Tensor Algebra -/

structure TensorAlgebra (F : Field) (V : VectorSpace F) where
  carrier : Type u
  T₀ : F.carrier → carrier      -- degree 0
  T₁ : V.V → carrier            -- degree 1
  mul : carrier → carrier → carrier
  -- Universal property: any linear map V → A (where A is an F-algebra)
  -- lifts uniquely to an algebra map T(V) → A

/-! ## Symmetric Algebra -/

structure SymmetricAlgebra (F : Field) (V : VectorSpace F) where
  carrier : Type u
  ι : V.V → carrier
  mul : carrier → carrier → carrier
  commutative : ∀ (x y : carrier), mul x y = mul y x
  -- Quotient of T(V) by ideal generated by (x⊗y - y⊗x)

/-! ## Exterior Algebra -/

structure ExteriorAlgebra (F : Field) (V : VectorSpace F) where
  carrier : Type u
  ι : V.V → carrier
  wedge : carrier → carrier → carrier
  antiComm : ∀ (x y : V.V), wedge (ι x) (ι y) = (TensorAlgebra.mul (TensorAlgebra F V)).T₀ (F.neg F.one) -- conceptual
  -- Quotient of T(V) by ideal generated by (x⊗x)

notation:70 x:70 " ∧ " y:70 => ExteriorAlgebra.wedge _ x y

/-! ## Exterior Power -/

def exteriorPower (F : Field) (V : VectorSpace F) (k : Nat) : Prop := True
  -- The k-th exterior power ⋀ᵏV

#eval "Core.Basic: TensorProduct, TensorAlgebra, SymmetricAlgebra, ExteriorAlgebra"
